language: cpp
compiler:
  - clang
  - gcc
  
before_script:
  - mkdir _build
  - cd _build
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev google-mock
  
script:
  cmake .. -DCMAKE_BUILD_TYPE=Debug &&
  make -j 16 &&
  Test/Tester
  
